function airmarDataWSTC = airMarSummary(airmarData)

airmarData = airmarData(:,{'latitudeCoordinate',...
                           'longitudeCoordinate',...
                           'airTemperature',...
                           'relativeHumidity',...
                           'dewPoint',...
                           'barrometricPressureBars_mintsDataYxxdr'
                           });

airmarDataWSTC     = gpsCropCoord(airmarData,32.992179, -96.757777,0.0015,0.0015);

airmarDataWSTC     = removevars( airmarDataWSTC, {...
    'latitudeCoordinate'  ,...
    'longitudeCoordinate'  });

airmarDataWSTC.Properties.VariableNames =    ...
    {'temperature_airmar',...
    'humidity_airmar'    ,...
    'dewPoint_airmar'    ,...
    'pressure_airmar'};

end

