function  valid = drawContourPlot(calibrated,nodeID,xLabel,yLabel,titleIn,givenDate,calibratedFolder,stringIn)
% (dataX,dataY,nodeID,xLabel,yLabel,titleIn,givenDate,calibratedFolder,stringIn,autoScaleOn,limit)
%DRAWCONTOURPLOT Summary of this function goes here
%   Detailed explanation goes here

    if(height(calibrated)>1)

        figure_1= figure('Tag','Contour_Plot',...
                'NumberTitle','off',...
                'units','pixels','OuterPosition',[0 0 900 675],...
                'Name','TimeSeries',...
                'Visible','off'...
            );

        contourOut = {...
                  'bin0',...
                  'bin1',...
                  'bin2',...
                  'bin3',...
                  'bin4',...
                  'bin5',...
                  'bin6',...
                  'bin7',...
                  'bin8',...
                  'bin9',...
                  'bin10',...
                  'bin11',...
                  'bin12',...
                  'bin13',...
                  'bin14',...
                  'bin15',...
                  'bin16',...
                  'bin17',...
                  'bin18',...
                  'bin19',...
                  'bin20',...
                  'bin21',...
                  'bin22',...
                  'bin23',...
                  };

              binBoundriesHigh = [.46,.66,1,1.3,1.7,2.3,3.0,4.0,5.2,6.5,8,10,12,14,16,18,20,22,25,28,31,34,37,40];
              binBoundriesLow  = [0.35,.46,.66,1,1.3,1.7,2.3,3.0,4.0,5.2,6.5,8,10,12,14,16,18,20,22,25,28,31,34,37];
              binCentersPre        = (binBoundriesHigh+binBoundriesLow)./2;


              latitudeStringPre = sprintf('%0.8f',calibrated.latitude_GPSGPGGA(1));
              longitudeStringPre =sprintf('%0.8f',calibrated.longitude_GPSGPGGA(1));
              latitudeString = strcat(latitudeStringPre,"^o");
              longitudeString =strcat(longitudeStringPre,"^o");


              for n =1:length(binBoundriesHigh)
                  binCenters(n) = string(sprintf('%0.2f',binCentersPre(1,n)));
              end 


              timeIn = hours(calibrated.dateTime - dateshift(calibrated.dateTime(1), 'start', 'day'));
              calibratedTable = timetable2table(calibrated);
              calibratedArray = log10(table2array(calibratedTable(:,contourOut))+1);

              contourf(timeIn,[1:24],real(calibratedArray)',50,'LineStyle', 'None');
              yticks([1:1:24]);
              yticklabels(string(binCenters));
              ylabel(yLabel,'FontWeight','bold','FontSize',10);
              xlabel(xLabel,'FontWeight','bold','FontSize',10);
              Top_Title=strcat(strcat(titleIn,"(",latitudeString,",",longitudeString,")"));
              Bottom_Title = strcat("Node " +string(nodeID));
              title({" ";Top_Title;Bottom_Title},'FontWeight','bold');


              colormap(jet) ;map2 = colormap; map2(1,:) = 1; colormap(map2);
              c = colorbar;
              c.Label.String = 'log_{10}(Particle Counts)';
              outFigNamePre    = strcat(calibratedFolder,"/",nodeID,"/",...
                                                             num2str(year(givenDate),'%04d'),"/",...
                                                             num2str(month(givenDate),'%02d'),"/",...
                                                             num2str(day(givenDate),'%02d'),"/",...
                                                             "MINTS_",...
                                                             nodeID,...
                                                             "_",stringIn,"_",...
                                                             num2str(year(givenDate),'%02d'),"_",...
                                                             num2str(month(givenDate),'%02d'),"_",...
                                                             num2str(day(givenDate),'%02d')...
                                                             );  

            folderCheck(fileparts(outFigNamePre));
            Fig_name = strcat(outFigNamePre,'.png');
            saveas(figure_1,char(Fig_name));
% 
%             Fig_name = strcat(outFigNamePre,'.fig')
%             saveas(figure_1,char(Fig_name));
          
            valid =  true ;
    end   
        
    valid = false;
end

