
function mintsData = GPRMCReadUtd(fileName,timeSpan)
    %% Import data from text file
    % Script for importing data from the following text file:
    %
    %    filename: /media/teamlary/teamlary1/gitHubRepos/carMintsML/firmware/dataProcessing/MINTS_001e0610c2e7_GPSGPRMC1_2020_04_04.csv
    %
    % Auto-generated by MATLAB on 26-Aug-2020 10:40:43

    %% Setup the Import Options and import the data
    opts = delimitedTextImportOptions("NumVariables", 13);

    % Specify range and delimiter
    opts.DataLines = [2, Inf];
    opts.Delimiter = ",";

    % Specify column names and types
    opts.VariableNames = ["dateTime", "timestamp", "status", "latitudeCoordinate", "longitudeCoordinate", "latitude", "latitudeDirection", "longitude", "longitudeDirection", "speedOverGround", "trueCourse", "dateStamp", "magVariationDirection"];
    opts.VariableTypes = ["datetime", "datetime", "categorical", "double", "double", "double", "categorical", "double", "categorical", "double", "string", "datetime", "string"];

    % Specify file level properties
    opts.ExtraColumnsRule = "ignore";
    opts.EmptyLineRule = "read";

    % Specify variable properties
    opts = setvaropts(opts, ["trueCourse", "magVariationDirection"], "WhitespaceRule", "preserve");
    opts = setvaropts(opts, ["status", "latitudeDirection", "longitudeDirection", "trueCourse", "magVariationDirection"], "EmptyFieldRule", "auto");
    opts = setvaropts(opts, "dateTime", "InputFormat", "yyyy-MM-dd HH:mm:ss.SSS");
    opts = setvaropts(opts, "timestamp", "InputFormat", "HH:mm:ss");
    opts = setvaropts(opts, "dateStamp", "InputFormat", "yyyy-MM-dd");

    % Import the data
    mintsData = readtable(fileName, opts);
        
    mintsData = removevars( mintsData,{...    
                    'timestamp',...
                    'status'               ,...
                    'latitude'             ,...
                    'latitudeDirection'    ,...
                    'longitude'            ,...
                    'longitudeDirection'   ,...
                    'speedOverGround'      ,...
                    'trueCourse'           ,...
                    'dateStamp'            ,...
                    'magVariationDirection'}...
                    );
        
    mintsData.dateTime.TimeZone = "utc";

    mintsData   =  rmmissing(retime(table2timetable(mintsData),'regular',@nanmean,'TimeStep',timeSpan));

%     mintsData.altitude(:) =  nan;
    
%     fileParts = strsplit(fileName,'_');
%     mintsData.sensor(:) =fileParts(end-3);

    
 %% Clear temporary variables
    clear opts      

end
