function mintsDataUTD = gpsCoordAdder(mintsDataUTD,timeStart, timeEnd, lat,lon)
% The current function adds GPS Coordinates to a given time table 
mintsDataUTD.GPSGPGGA2_latitudeCoordinate(...
        mintsDataUTD.dateTime<timeEnd&...
        mintsDataUTD.dateTime>timeStart,:)=lat;

mintsDataUTD.GPSGPGGA2_longitudeCoordinate(...
        mintsDataUTD.dateTime<timeEnd&...
        mintsDataUTD.dateTime>timeStart,:)=lon;

mintsDataUTD.GPSGPGGA2_latitudeCoordinate(...
    mintsDataUTD.GPSGPGGA2_latitudeCoordinate==0,:)= nan;    

mintsDataUTD.GPSGPGGA2_longitudeCoordinate(...
    mintsDataUTD.GPSGPGGA2_longitudeCoordinate==0,:)= nan;

end 