function [] = printCSVT(calibrated,folder,nodeID,givenDate,stringIn)
%PRINTCSVDAILY Summary of this function goes here
                    
    outCalibratedFileName    = strcat(folder,"/",nodeID,"/",...
                                                     num2str(year(givenDate),'%04d'),"/",...
                                                     num2str(month(givenDate),'%02d'),"/",...
                                                     num2str(day(givenDate),'%02d'),"/",...
                                                     "MINTS_",...
                                                     nodeID,...
                                                     "_",stringIn,"_",...
                                                     num2str(year(givenDate),'%04d'),"_",...
                                                     num2str(month(givenDate),'%02d'),"_",...
                                                     num2str(day(givenDate),'%02d'),".csv"...
                                                 );  
                                             

    folderCheck(outCalibratedFileName)
    writetable(calibrated,outCalibratedFileName)
end
