
function [] = timeSeriesPlotsTLL(calibrated,...
                                        nodeID,...
                                            givenDate,...
                                                calibratedFolder,...
                                                    timeZone)
%DRAWALLTIMESERIESPLOTS Summary of this function goes here
%   Detailed explanation goes here
% givenDate         = period(dateIndex);
latitudeStringPre = sprintf('%0.8f',calibrated.Latitude(end));
longitudeStringPre =sprintf('%0.8f',calibrated.Longitude(end));
latitudeString = strcat(latitudeStringPre,"^o");
longitudeString =strcat(longitudeStringPre,"^o");


    drawTimeSeriesWithSave2(...
                    calibrated.dateTime,...
                    calibrated.PM1,...
                    nodeID,...
                    strcat(timeZone," Time"),...
                    "PM_{1}(\mug/m^{3})",...
                    strcat("PM_{1} (",latitudeString,",",longitudeString,")"),...
                    givenDate,...
                    calibratedFolder,...
                    strcat("PM1_",timeZone,"_Time"),...
                    false,...
                    100 ...
                    );
                
    drawTimeSeriesWithSave2(...
                    calibrated.dateTime,...
                    calibrated.PM2_5,...
                    nodeID,...
                    strcat(timeZone," Time"),...
                    "PM_{2.5}(\mug/m^{3})",...
                    strcat("PM_{2.5} (",latitudeString,",",longitudeString,")"),...
                    givenDate,...
                    calibratedFolder,...
                    strcat("PM2_5_",timeZone,"_Time"),...
                    false,...
                    100 ...
                    );
    
    drawTimeSeriesWithSave2(...
                    calibrated.dateTime,...
                    calibrated.PM4,...
                    nodeID,...
                    strcat(timeZone," Time"),...
                    "PM_{4}(\mug/m^{3})",...
                    strcat("PM_{4} (",latitudeString,",",longitudeString,")"),...
                    givenDate,...
                    calibratedFolder,...
                    strcat("PM4_",timeZone,"_Time"),...
                    false,...
                    100 ...
                    );
                            
        drawTimeSeriesWithSave2(...
                    calibrated.dateTime,...
                    calibrated.PM10,...
                    nodeID,...
                    strcat(timeZone," Time"),...
                    "PM_{10}(\mug/m^{3})",...
                    strcat("PM_{10} (",latitudeString,",",longitudeString,")"),...
                    givenDate,...
                    calibratedFolder,...
                    strcat("PM10_",timeZone,"_Time"),...
                    false,...
                    100 ...
                    );

        drawTimeSeriesWithSave2(...
                    calibrated.dateTime,...
                    calibrated.PMTotal,...
                    nodeID,...
                    strcat(timeZone," Time"),...
                    "PM_{Total}(\mug/m^{3})",...
                    strcat("PM_{Total} (",latitudeString,",",longitudeString,")"),...
                    givenDate,...
                    calibratedFolder,...
                    strcat("PMTotal_",timeZone,"_Time"),...
                    false,...
                    100 ...
                    )            ;    
         drawTimeSeriesWithSave2(...
                    calibrated.dateTime,...
                    calibrated.ParticleConcentration,...
                    nodeID,...
                    strcat(timeZone," Time"),...
                    "Particle Concentration(P/m^{3})",...
                    strcat("Particle Concentration (",latitudeString,",",longitudeString,")"),...
                    givenDate,...
                    calibratedFolder,...
                    strcat("Particle Concentration_",timeZone,"_Time"),...
                    false,...
                    100 ...
                    ) ;
                   
         drawTimeSeriesWithSave2(...
                    calibrated.dateTime,...
                    calibrated.Temperature,...
                    nodeID,...
                    strcat(timeZone," Time"),...
                    "Temperature",...
                    strcat("Temperature (",latitudeString,",",longitudeString,")"),...
                    givenDate,...
                    calibratedFolder,...
                    strcat("Temperature_",timeZone,"_Time"),...
                    false,...
                    100 ...
                    ) 
          
         drawTimeSeriesWithSave2(...
                    calibrated.dateTime,...
                    calibrated.Humidity,...
                    nodeID,...
                    strcat(timeZone," Time"),...
                    "Humidity",...
                    strcat("Humidity (",latitudeString,",",longitudeString,")"),...
                    givenDate,...
                    calibratedFolder,...
                    strcat("Humidity_",timeZone,"_Time"),...
                    false,...
                    100 ...
                    )           ;      
          
         drawTimeSeriesWithSave2(...
                    calibrated.dateTime,...
                    calibrated.Pressure,...
                    nodeID,...
                    strcat(timeZone," Time"),...
                    "Pressure",...
                    strcat("Pressure (",latitudeString,",",longitudeString,")"),...
                    givenDate,...
                    calibratedFolder,...
                    strcat("Pressure_",timeZone,"_Time"),...
                    false,...
                    100 ...
                    )      ;     
                
                  
         drawTimeSeriesWithSave2(...
                    calibrated.dateTime,...
                    calibrated.DewPoint,...
                    nodeID,...
                    strcat(timeZone," Time"),...
                    "Dew Point",...
                    strcat("Dew Point (",latitudeString,",",longitudeString,")"),...
                    givenDate,...
                    calibratedFolder,...
                    strcat("DewPoint_",timeZone,"_Time"),...
                    false,...
                    100 ...
                    )    ;
                
         drawTimeSeries5x(...
                    calibrated.dateTime,...
                    calibrated.PM1,...
                    calibrated.dateTime,...
                    calibrated.PM2_5,...
                    calibrated.dateTime,...
                    calibrated.PM4,...
                    calibrated.dateTime,...
                    calibrated.PM10,...
                    calibrated.dateTime,...
                    calibrated.PMTotal,...
                    "PM_{1}","PM_{2.5}","PM_{4}","PM_{10}","PM_{Total}",...
                    nodeID,...
                    strcat(timeZone," Time"),...
                    "PM (\mug/m^{3})",...
                    strcat("Particulate Matter (",latitudeString,",",longitudeString,")"),...
                    givenDate,...
                    calibratedFolder,...
                    strcat("PM_",timeZone,"_Time"),...
                    false,...
                    100 ...
                    )    ;        
                