function mintsData = importResultsFile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  MINTS001E06318CEECALIBRATED20210701 = IMPORTFILE(FILENAME) reads data
%  from text file FILENAME for the default selection.  Returns the data
%  as a table.
%
%  MINTS001E06318CEECALIBRATED20210701 = IMPORTFILE(FILE, DATALINES)
%  reads data for the specified row interval(s) of text file FILENAME.
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  MINTS001e06318ceecalibrated20210701 = importfile("/home/teamlary/mnt/teamlary1/mintsData/laryTempResults/diagnosis/MINTS_001e06318cee_calibrated_2021_07_01.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 19-Jul-2021 18:10:11

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 30);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["dateTime", "Latitude", "Longitude", "Altitude", "Bin0", "Bin1", "Bin2", "Bin3", "Bin4", "Bin5", "Bin6", "Bin7", "Bin8", "Bin9", "Bin10", "Bin11", "Bin12", "Bin13", "Bin14", "Bin15", "PM1", "PM2_5", "PM4", "PM10", "PMTotal", "ParticleConcentration", "Temperature", "Humidity", "DewPoint", "Pressure"];
opts.VariableTypes = ["datetime", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "dateTime", "InputFormat", "yyyy-MM-dd HH:mm:ss.SSS",'timezone','utc');

% Import the data
mintsData = readtable(filename, opts);

end