 
dataDate= datetime('today','timezone','utc') - days(200);
lk = mintsDataUTD(year(mintsDataUTD.dateTime) == year(dataDate)&...
         month(mintsDataUTD.dateTime) == month(dataDate)&...
            day(mintsDataUTD.dateTime) == day(dataDate),:);
