function out = epaDownload(parametor,...
                              beginDate,endDate,...
                                state,county,site,...
                                   email,key)
% Download Data from EPA Sensors 
% lk = strcat("https://aqs.epa.gov/data/api/sampleData/bySite?email=",...
%                                                                 email,"&key=",key,...
%                                                                 "&param=",parametor,...
%                                                                 "&bdate=",beginDate,...
%                                                                 "&edate=",endDate,...
%                                                                 "&state=",state,...
%                                                                 "&county=",county,...
%                                                                 "&site=",site)
%                                                             display(lk)
  data = webread(strcat("https://aqs.epa.gov/data/api/sampleData/bySite?email=",...
                                                                email,"&key=",key,...
                                                                "&param=",parametor,...
                                                                "&bdate=",beginDate,...
                                                                "&edate=",endDate,...
                                                                "&state=",state,...
                                                                "&county=",county,...
                                                                "&site=",site));
% data2017 = webread("https://aqs.epa.gov/data/api/sampleData/bySite?email=lakithaomal@gmail.com&key=ochreram73&param=88101&bdate=20170101&edate=20171231&state=48&county=439&site=1006")

for n = 1: length(data.Data)
   dateIn_bam(n,:) = data.Data(n).date_gmt;
   timeIn_bam(n,:) = data.Data(n).time_gmt;
   latitude_bam(n,:) = data.Data(n).latitude;
   longitude_bam(n,:) = data.Data(n).longitude;
   
   if(isempty(data.Data(n).sample_measurement))
   pm2_5_bam(n,:) =  NaN;
   else
   pm2_5_bam(n,:) =data.Data(n).sample_measurement;
   end
end

dateTime_bam = strcat(dateIn_bam," ",timeIn_bam);

dateTime = datetime(dateTime_bam,'timezone','utc');

out = timetable(dateTime,pm2_5_bam,latitude_bam,longitude_bam);

end

