
function resultsCurrent  = plottingAllGraphsV2(plotsFolder,nodeID,target,...
                            dailyString,versionStr,...
                            outTrainEstimate,outValidEstimate,...
                            trainingTT,validatingTT,...
                            Out_Train,Out_Validation,...
                            units,targetLabel,...
                            limitsLow,limitsHigh,...
                            targetIndex,graphTitle1,...
                            instrument)

%% Get Statistics
display(newline);
combinedFigDaily   = getFileNameFigure(plotsFolder,nodeID,target,dailyString)
folderCheck(combinedFigDaily)

combinedFig        = strrep(combinedFigDaily,dailyString,strcat(versionStr,"/",versionStr));
folderCheck(combinedFig)

% Adding a Time Series Plot (02,21,2021)
combinedFigTT        = strrep(combinedFig,".png",...
    "_TT.png")

drawTimeSeries3x(trainingTT.dateTime,outTrainEstimate,...
    validatingTT.dateTime,outValidEstimate,...
    [trainingTT.dateTime;validatingTT.dateTime],...
    [Out_Train;Out_Validation],...
    "Training Estimates","Testing Estimates ",instrument,...
    nodeID,"Date Time (UTC)",...
    targetLabel +" ("+ units{targetIndex}+ ")",...
    targetLabel + " Calibration ("+strrep(versionStr,"_"," ")+")",...
    combinedFigTT)

graphTitle2 = strcat(" ");

drawScatterPlotMintsCombinedLimitsUTD(Out_Train,...
    outTrainEstimate,...
    Out_Validation,...
    outValidEstimate,...
    limitsLow{targetIndex},...
    limitsHigh{targetIndex},...
    nodeID,...
    targetLabel,...
    instrument,...
    "UTD Node",...
    units{targetIndex},...
    combinedFigDaily,...
    graphTitle1,...
    graphTitle2);

resultsCurrent=drawScatterPlotMintsCombinedLimitsUTD(Out_Train,...
    outTrainEstimate,...
    Out_Validation,...
    outValidEstimate,...
    limitsLow{targetIndex},...
    limitsHigh{targetIndex},...
    nodeID,...
    targetLabel,...
    instrument,...
    "UTD Node",...
    units{targetIndex},...
    combinedFig,...
    graphTitle1,...
    graphTitle2);